"""sync fixes: content_key, opening balance anchor, run lock

Revision ID: a7fb93e3d818
Revises: b682d94622db
Create Date: 2026-09-09 02:26:59.175860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7fb93e3d818'
down_revision: Union[str, Sequence[str], None] = 'b682d94622db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opening_balance_source', sa.Enum('entered', 'derived_at_link', name='opening_balance_source'), server_default='entered', nullable=False))
        batch_op.add_column(sa.Column('opening_balance_derived_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.create_index('uq_sync_run_running', ['status'], unique=True, sqlite_where=sa.text("status = 'running'"))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_key', sa.String(), nullable=True))
        batch_op.create_index('ix_transactions_content_key', ['content_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_content_key')
        batch_op.drop_column('content_key')

    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index('uq_sync_run_running', sqlite_where=sa.text("status = 'running'"))

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('opening_balance_derived_at')
        batch_op.drop_column('opening_balance_source')

    # ### end Alembic commands ###
