"""bank sync: account/transaction sync fields, sync_runs

Revision ID: b682d94622db
Revises: dd59e54df277
Create Date: 2026-09-09 01:20:28.921980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b682d94622db'
down_revision: Union[str, Sequence[str], None] = 'dd59e54df277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ok', 'partial', 'failed', name='sync_status'), nullable=False),
    sa.Column('accounts_synced', sa.Integer(), nullable=False),
    sa.Column('added', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sync_source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_account_sync_external', ['sync_source', 'external_id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.Enum('manual', 'csv', 'sync', name='txn_source'), server_default='manual', nullable=False))
        batch_op.add_column(sa.Column('pending', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_unique_constraint('uq_txn_account_external', ['account_id', 'external_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_txn_account_external', type_='unique')
        batch_op.drop_column('pending')
        batch_op.drop_column('source')
        batch_op.drop_column('external_id')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_account_sync_external', type_='unique')
        batch_op.drop_column('last_synced_at')
        batch_op.drop_column('sync_source')
        batch_op.drop_column('external_id')

    op.drop_table('sync_runs')
    # ### end Alembic commands ###
