"""soft delete: transactions.deleted_at, sync_runs.swept_count

Revision ID: e2bfed7246e2
Revises: 842a8d52a63a
Create Date: 2026-09-09 15:05:21.345514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2bfed7246e2'
down_revision: Union[str, Sequence[str], None] = '842a8d52a63a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('swept_count', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_column('swept_count')

    # ### end Alembic commands ###
